INI_FILES="./flow_gmsh.con flow_vtk.con flow_implicit_fields_gmsh.con flow_implicit_old.con flow_lin_sorption_dg.con"
#INI_FILES="flow_implicit_old.con"
NPROC="1 2"
FLOW_PARAMS="-o output"

include ../all_tests.mk
