#!/bin/bash
# Simple script which will use correct python version and execute runtest.py

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#  populated by configure_file call
/usr/bin/python3 ${SCRIPT_DIR}/../src/py123d/bin/runtest.py "$@"
