INI_FILES="flow_M_Tr_both.ini"	// name of ini file
NPROC="1"	// number of procs
TEST_DIR="11_reactional_transport_semchem"	// name of test dir

test:
	cd ..;\
	./run_test.sh ${INI_FILES} ${NPROC} ${TEST_DIR} 