#! /bin/bash	
echo
echo "##########      08_steady_flow_sources: MESH and NGH and BCD         ## Start ##"
echo

# path to trunk/bin to NGH and BCD programs
NGH=../../bin/ngh/bin/ngh
BCD=../../bin/bcd/bin/bcd

# name of test, used for gmsh
NAME="test08"

# actual reference output is computed for mesh in input
# mesh generated by actual geo file is little bit different
# so make test will fail while comparing

# meshing geo file
# gmsh -2 -o input/$NAME.msh -format msh $NAME.geo

# generating neighbouring
$NGH ./ngh.ini

# preparing boundary condition files (flow, transport)
$BCD ./bcd.ini

echo
echo "##########      08_steady_flow_sources: MESH and NGH and BCD         ### End ###"
echo


