INI_FILES="flow_vtk.yaml output_input_fields.yaml output_multi_fields.yaml output_multi_fields_implicit.yaml flow_vtk_nobalance.yaml flow_implicit_dual_por.yaml"
NPROC="1 2"
FLOW_PARAMS="-o output"

include ../all_tests.mk