INI_FILES="flow_vtk.yaml flow_old_gmsh.yaml flow_old_vtk.yaml flow_implicit.yaml output_input_fields.yaml flow_vtk_nobalance.yaml flow_implicit_nobalance.yaml"
NPROC="1 2"
FLOW_PARAMS="-o output"

include ../all_tests.mk