INI_FILES="flow_vtk.con flow_old_gmsh.con flow_old_vtk.con flow_implicit.con output_input_fields.con flow_vtk_nobalance.con flow_implicit_nobalance.con flow_vtk.yaml"
# INI_FILES="flow_vtk.con"
NPROC="1 2"
FLOW_PARAMS="-o output"

include ../all_tests.mk