 INI_FILES="test_20.con"
# INI_FILES="langmuir_new.con freundlich_new.con linear_new.con langmuir_old.con freundlich_old.con linear_old.con langmuir_var.con freundlich_var.con linear_var.con"
# INI_FILES="linear_new.con linear_old.con linear_var.con"
# INI_FILES="langmuir_old.con freundlich_old.con linear_old.con"
NPROC="1"
FLOW_PARAMS="-o output"

include ../all_tests.mk