INI_FILES="flow_vtk_simple.yaml flow_vtk_source.yaml test_20.yaml langmuir_new.yaml freundlich_new.yaml linear_new.yaml langmuir_var.yaml freundlich_var.yaml linear_var.yaml"
NPROC="1 2"
FLOW_PARAMS="-o output"



include ../all_tests.mk