name: Report unit test results
description: Report unit test results to GitHub
inputs:
  path-to-xml: 
    description: 'Path to the XML file containing the test results'
    required: true
    default: 'unit_tests/*.xml'
runs:
  using: 'composite'
  steps:
    - name: Test Reporter
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: "Test reporter"
        reporter: java-junit
        path:  ${{ inputs.path-to-xml }}
        token: ${{ secrets.GITHUB_TOKEN }}
        list-suites: 'failed'
        list-tests: 'failed'