INI_FILES="./flow_gmsh.yaml ./flow_vtk.yaml ./flow_vtk_piezo.yaml ./flow_old_vtk.yaml ./flow_vtk_fbc.yaml ./flow_vtk_nobalance.yaml ./flow_bddc.yaml"
NPROC="1 2 3"
FLOW_PARAMS="-i input -o output -ksp_monitor"

include ../all_tests.mk
