# ---------------------------------------------------------------------------- #
# ---------- MULTIJOB -------------------------------------------------------- #
# ---------------------------------------------------------------------------- #
name: "Flow123d-{environment}-debug-multijob"
display-name: "debug / Flow123d multijob"
project-type: multijob
defaults: flow123d-build
parameters:
  - string:
      name: BRANCH_NAME
      default: $GIT_BRANCH
      description: Specify the branch name you want to build. Default value will build master branch.
  - bool:
      name: SKIP_UNIT_TESTS
      default: false
      description: If true, will not run any unit-test
  - bool:
      name: SKIP_INT_TESTS
      default: false
      description: If true, will not run any int-test
  - bool:
      name: RUN_SERIAL_ONLY
      default: false
      description: If true, will only run only serial tests
block-downstream: yes
scm:
  - git:
      url: https://github.com/flow123d/flow123d.git
      reference-repo: /home/builder/git-cache/flow123d.git
      branches:
          - "*"
      basedir: flow123d
      browser: githubweb
      browser-url: https://github.com/flow123d/flow123d/
      skip-tag: true

wrappers:
  - inject:
      script-content: |
        rm -f prop.file && touch prop.file
        echo "BUILD_NAME=${{BRANCH_NAME#origin/}}@${{GIT_COMMIT:0:6}}" >> prop.file
        echo "_GIT_BRANCH=${{BRANCH_NAME#origin/}}"                    >> prop.file

  - build-name:
      name:  "${{PROPFILE,file=\"prop.file\",property=\"_GIT_BRANCH\"}}@${{GIT_REVISION, length=6}} #${{BUILD_NUMBER}}"

triggers:
  - github

builders:
  # ---------- START IMAGE ----------------------------------------------- #
  - multijob:
      name: "Build flow123d Phase"
      condition: SUCCESSFUL
      projects:
        - name: "Flow123d-{environment}-debug-build"
          current-parameters: true

  - multijob:
      name: "Unit tests"
      condition: COMPLETED
      projects:
        - {name: "Flow123d-{environment}-debug-unit-test-$PLACEHOLDER_unit_list$", current-parameters: true}

  - multijob:
      name: "Integration tests"
      condition: COMPLETED
      projects:
        - {name: "Flow123d-{environment}-debug-test-$PLACEHOLDER_test_list$", current-parameters: true}

  - multijob:
      name: "Make doc"
      condition: COMPLETED
      projects:
        - name: "Flow123d-{environment}-debug-make-doc"
          current-parameters: true
  # ---------- STOP IMAGE ------------------------------------------------ #
  - multijob:
      name: "Stop image"
      condition: COMPLETED
      projects:
        - name: "Flow123d-{environment}-debug-stop-image"
          current-parameters: true
