# ---------------------------------------------------------------------------- #
# ---------- UNIT-TESTS ------------------------------------------------------ #
# ---------------------------------------------------------------------------- #
name: "Flow123d-{environment}-{build-type}-unit-test-{unit-dir}" 
display-name: "{build-type} / Flow123d unit-test {unit-dir}"
defaults: flow123d-build
builders:
  - shell:
      unstable-return: 42
      command: |
        echo "SKIP_UNIT_TESTS = $SKIP_UNIT_TESTS"

        if [[ "$SKIP_UNIT_TESTS" = true ]] ; then
          echo "Skipping unit tests"
          exit 42
        fi

        docker exec cont{environment}{build-type} make -C ${{FLOW}}/build_tree/unit_tests/{unit-dir} -k all-test

publishers:
  - archive:
      artifacts: 'docker/tests/{test-dir}/**/*.log'
      allow-empty: true
