#InstallPetsc.cmake
#
# Created on: Jul 20, 2012
#     Author: jb
#
# accepted variables: 
#     PETSC_INSTALL_DIR - target directory used for instalation
#     PETSC_INSTALL_URL - url with petsc tarball
#     PETSC_INSTALL_MPI_DIR      - pass MPI dir to PETSC configure 
#     PETSC_INSTALL_LAPACK_DIR   - pass Blas/Lapack dir to PETSC configure
#
#     PETSC_INSTALL_CONFIG - possible values:
#       mini             - only petsc + necessary MPI, BLAS, LAPACK
#       flow123d_mini    - mini + metis + parmetis
#       bddcml           - flow123d_mini + mumps + scalapack + blacs
#       full             - bddcml + hypre + blopex + umfpack + sundials
#       default)         = flow123d_mini
#
#     PETSC_INSTALL_ADD_OPTIONS - additional options used as parameters to configure.py,
#     PETSC_INSTALL_OWN_OPTIONS - use only this varieble as configure options
#
# We automatically reuse compiler and their flags. Further we set "--with-debugging=1" 
# if CMAKE_BUILD_TYPE == "debug", otherwise we turn debugging off.
#
# CAUTION: Never use semicolon a part of compiler options or PETSC_INSTALL_OPTIONS.


# set flags for PETSc, user specified are first choice, if not specified external libs flags will be used

if (NOT PERMON_INSTALL_DIR)
    set(PERMON_INSTALL_DIR "${EXTERNAL_PROJECT_DIR}/permon_build")
endif()    

##########################################################################
# Download PERMON
# A temporary CMakeLists.txt
# create CMakeLists.txt for external project
set (cmakelists_fname "${PERMON_INSTALL_DIR}/CMakeLists.txt")
file (WRITE "${cmakelists_fname}"
"
  ## This file was autogenerated by InstallPERMON.cmake
  cmake_minimum_required(VERSION 2.8)
  include(ExternalProject)
  ExternalProject_Add(PERMON
    DOWNLOAD_DIR ${PERMON_INSTALL_DIR} 
    URL ${PERMON_INSTALL_URL}
    SOURCE_DIR ${PERMON_INSTALL_DIR}/src
    BINARY_DIR ${PERMON_INSTALL_DIR}/src
    BUILD_COMMAND make
    INSTALL_COMMAND \"\"
  )  
")

# TODO rebuilds?
## create configuration script (overcome troubles with two expansion levels)
#file(WRITE "${PETSC_INSTALL_DIR}/conf_tmp.sh"
#"
#cd ${PETSC_INSTALL_DIR}/src
#export CC=${CMAKE_C_COMPILER}
#export CXX=${CMAKE_CXX_COMPILER}
#export FC=${PETSC_Fortran_COMPILER}
#./configure  --with-make-np ${MAKE_NUMCPUS} ${EXPAND_CONF_LINE}
#")
#
## avoid unnecessary rebuilds if configuration doesn't change
#execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different "${PETSC_INSTALL_DIR}/conf_tmp.sh" "${PETSC_INSTALL_DIR}/conf.sh")



message(STATUS "=== Installing PERMON ===")
# run cmake
set(PERMON_DIR "${PERMON_INSTALL_DIR}/src")
set(PERMON_ARCH "flow123d_release")
set(ENV{PERMON_DIR} "${PERMON_DIR}")
set(ENV{PERMON_ARCH} "${PERMON_ARCH}")
execute_process(COMMAND ${CMAKE_COMMAND} ${PERMON_INSTALL_DIR} 
      WORKING_DIRECTORY ${PERMON_INSTALL_DIR})

find_program (MAKE_EXECUTABLE NAMES make gmake)
# run make
execute_process(COMMAND ${MAKE_EXECUTABLE} VERBOSE=1 PERMON
      WORKING_DIRECTORY ${PERMON_INSTALL_DIR})    


#file (REMOVE ${cmakelists_fname})

message(STATUS "== PERMON build done")

