#!/bin/bash

echo "-- Editing PYTHONPATH variable"
# get absolute dir in which is this script stored
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# populated by configure_file in cmake call
PYTHONPATHS="@PY_WRAPPER_PATHS@"

# temporatily set for separator to colon (;)
export IFS=";"
for path in $PYTHONPATHS
do
   # add all paths to PYTHONPATH variable
   PYTHONPATH=${PYTHONPATH}:${SCRIPT_DIR}/../build_tree${path}
done
# restore separator
export IFS=
# export python PYTHONPATH variable
export PYTHONPATH=${PYTHONPATH}
"$@"