
TEST_OBJS= \
$(OBJS)/system.o \
$(OBJS)/xio.o \
$(OBJS)/read_ini.o \
$(OBJS)/sys_function_stack.o 

include ../makefile


#test: test.cpp ../../src/system.cc
#	${CPP} ${INCLUDE} test.cpp -o test ../../src/system.cc