INI_FILES="./flow_dirichlet.yaml ./flow_neumann.yaml ./flow_robin.yaml ./flow_total_flux.yaml ./flow_seepage.yaml ./flow_river_square.yaml"
NPROC="1 2"
FLOW_PARAMS="-o output -i input"
include ../all_tests.mk
